services:
  furniture-api:
    container_name: furniture-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/furniture
    working_dir: /usr/src/furniture

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  furniture-batch:
    container_name: furniture-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/furniture
    working_dir: /usr/src/furniture

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
#furniture-next: localhost:4000 <=> container:3000
#furniture-api: localhost:4001 <=> container:3007
#furniture-batch: localhost:4002 <=> container:3008

# docker compose up -d
# docker compose stop
# docker compose start
# docker compose restart
# docker compose stop && docker compose rm -f
